apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  chart:
    spec:
      chart: coredns
      version: 1.36.0
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: coredns-values
