fail_fast: false
repos:
  - repo: local
    hooks:
      - id: treefmt
        name: format
        language: system
        entry: treefmt
        types: [text]
  - repo: https://github.com/mgaruccio/pre-commit-hook-ensure-sops
    rev: v1.2
    hooks:
      - id: sops-encryption
        files: "\\w+\\.sops\\."
