apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-cluster
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/ModestMeowth/kube.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    !/apps
    !/flux
    !/monitoring
    !/network
    !/storage
