apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname coredns
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: ./cluster/apps/kube-system/coredns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-cluster
  wait: true
